---
title: "DataGov"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(knitr)
library(tidyr)
library(dplyr)
literacy <- read.csv("Education.csv", check.names = F)
tourism <- read.csv("Tourism.csv", check.names = F)
```


###Literacy by Region
```{r Tidy data and create plot}
literacy.long <- gather(literacy, "year", "n", 2:8)

literacy.long$year <- as.numeric(literacy.long$year)

literacy.long %>% group_by(Region, year) %>% 
  summarise(total = mean(n)) %>% 
  filter(!is.na(total)) %>% 
  ggplot(aes(x = year, y = total, colour = Region)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(1951, 2011, 10)) +
  scale_y_continuous(breaks = seq(0, 100, 5))

```


###Tourists in India 
```{r}
tourism.long <- gather(tourism, "year", "number", 3:12)

tourism.long$year <- as.numeric(tourism.long$year)

tourism.long %>% filter(!is.na(tourism.long$number)) %>% 
  group_by(year, region) %>% 
  summarise(totalNumber = sum(number)) %>% 
  ggplot(aes(x = year, y = totalNumber, colour = region)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(2000, 2010, 1))

```
Notes: We see a drop in the incoming tourists after 2008 possibly because of the Mumbai terror attacks. Now we will look at the tourist data from some specific countries.

```{r Tourists from specific countries}
countries <- c ("U.S.A.", "Canada", "Argentina", "Brazil", "Belgium", "France", "Germany", 
                "Netherland", "Spain", "Portugal", "U.K.", "Mali", "Egypt", "South Africa",
                "Nigeria", "China", "Japan", "Korea", "Singapore", "Nepal", "Bangladesh",
                "Pakistan")

tourism.long %>% filter(country %in% countries & !is.na(tourism.long$number)) %>% 
  ggplot(aes(x = year, y = number, colour = country)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(2001, 2010, 1)) +
  scale_y_continuous(breaks = seq(0, 900000, 50000))
```

